### ISSUE TITLE
Connector gave error

### ISSUE THREAD

**Issue by scatterinstruments** [tstoddart/odoo-woocommerce-connector#1]
when i create connection 
![Screenshot_6](https://user-images.githubusercontent.com/72292796/95336093-ae42e380-08c9-11eb-94b9-762233029b90.png)
![Screenshot_5](https://user-images.githubusercontent.com/72292796/95336096-b00ca700-08c9-11eb-943f-f72aba1d7913.png)

with odoo and woocommerce got this error

Error:
Odoo Server Error

Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/http.py", line 624, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/odoo/odoo-server/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/odoo/odoo-server/odoo/tools/pycompat.py", line 14, in reraise
    raise value
  File "/odoo/odoo-server/odoo/http.py", line 669, in dispatch
    result = self._call_function(**self.params)
  File "/odoo/odoo-server/odoo/http.py", line 350, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/odoo/odoo-server/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/odoo/odoo-server/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 915, in __call__
    return self.method(*args, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 1326, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 1314, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/odoo/odoo-server/odoo/api.py", line 383, in call_kw
    result = _call_kw_model(method, model, args, kwargs)
  File "/odoo/odoo-server/odoo/api.py", line 356, in _call_kw_model
    result = method(recs, *args, **kwargs)
  File "/odoo/custom/addons/odoo-woocommerce-connector-main/models/models.py", line 52, in sync_woocommerce
    ids = ','.join(ids_arr)
TypeError: sequence item 0: expected str instance, int found

**Comment by chrisandrewmann** [comment]
Had the same error, replace 3 x lines with:

ids = ','.join(map(str, ids_arr))
